---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  notify: start nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: true

- handlers:
  name: start nginx
    service:
      name: nginx
      state: started