---
- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
  notify: start docker

- name: Ensure Docker is running
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: true

handlers:
  - name: start docker
    service:
      name: "{{ docker_service }}"
      state: started