---
- name: Установка Docker и запуск приложения
  hosts: app
  become: yes
  tasks:
    - name: Установка необходимых пакетов
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Добавление GPG ключа
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление репозитория Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present

    - name: Обновление кэша apt
      apt:
        update_cache: yes

    - name: Установка Docker
      apt:
        name: docker-ce
        state: present

    - name: Убедитесь, что Docker работает
      service:
        name: docker
        state: started
        enabled: yes

    - name: Запуск Django приложения в Docker
      community.docker.docker_container:
        name: django_app
        image: timurbabs/django
        state: started
        ports:
          - "8000:8000"
        restart_policy: always